# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatter',
            name='chat_field',
            field=models.CharField(max_length=400),
        ),
    ]
