# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-30 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_chatter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatter',
            name='user',
        ),
        migrations.AddField(
            model_name='chatter',
            name='receiver',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
