# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-30 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20181030_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatter',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chatter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
