# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-31 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20181030_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatter',
            name='receiver',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
